Upgrade balena-preload to 13.0.0
balena-io/balena-cli pull request #2573
Opened 2022-12-22 13:39 UTC by aethernet

Drops ability to preload Intel Edison (EOL 2017)

Change-type: major

2022-12-28 14:39 UTC, klutchell requested changes
Can you please change your commit format to look like [this](https://github.com/balena-io/balena-cli/commit/2b2c40c22d15d765f19b421976113939ec4fc455)?

The last few versions were not formatted correctly and this breaks nested changelogs.

Unfortunately that process is not documented well, if at all.

2022-12-28 14:40 UTC, klutchell commented
Have we asked CS how many Intel Edison devices are still registered to balenaCloud?

What about openBalena and balenaMachine users that might have these devices?

2023-01-02 08:49 UTC, aethernet commented
Context is here :
- https://balena.zulipchat.com/#narrow/stream/345889-loop.2Fbalena-os/topic/Intel.20Edison/near/310245867

Both balenaCloud and openBalena users can use the latest version with Edison support.

IMHO if we don't clean up exceptions when deprecating DT, we'll never do it. Should be part of the process.

2023-01-02 14:15 UTC, klutchell approved these changes

2023-01-02 15:20 UTC, merged